version: '3'
services:
  mongo:
    hostname: mongo
    image: mongo
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - erxes-net
    volumes:
      - ./data/db:/data/db
    command: "--bind_ip_all --replSet rs0"

  redis:
    image: 'redis'
    container_name: redis
    networks:
      - erxes-net

  rabbitmq:
    image: rabbitmq:3.7.17-management
    container_name: rabbitmq
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
    networks:
      - erxes-net
    # RabbitMQ data will be saved into ./rabbitmq-data folder.
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.2"
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - erxes-net
    volumes:
      - ./elasticsearchData:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.5.2"
    container_name: "kibana"
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - erxes-net

  erxes-api:
    container_name: "erxes-api"
    build:
      dockerfile: ./Dockerfile.dev
      context: ../erxes-api
    volumes:
      - /erxes-api/node_modules
      - /erxes-api/.git
      - ../erxes-api/:/erxes-api
    env_file:
      ../erxes-api/.env
    depends_on:
      - "mongo"
      - "redis"
      - "rabbitmq"
      - "elasticsearch"
    ports:
      - '3300:3300'
    networks:
      - erxes-net

  elksyncer:
    image: "elksyncer"
    container_name: "elksyncer"
    env_file:
      ../erxes-api/elkSyncer/.env
    depends_on:
      - "mongo"
      - "elasticsearch"
    volumes:
      - ../erxes-api/elkSyncer:/elkSyncer
    command: ["./wait-for.sh", "elasticsearch:9200", "--", "python", "main.py"]
    networks:
      - erxes-net

networks:
  erxes-net:
    driver: bridge