version: '3'
services:
  mongo:
    image: "mongo"
    container_name: "mongo"
    volumes:
      - ./data/db:/data/db

  redis:
    image: 'redis'

  erxes-api:
    container_name: "erxes-api"
    build:
      dockerfile: ./Dockerfile.dev
      context: ../erxes-api
    volumes:
      - /erxes-api/node_modules
      - /erxes-api/.git
      - ../erxes-api/:/erxes-api
    env_file:
      ../erxes-api/.env
    depends_on:
      - "mongo"
      - "redis"
    ports:
      - '3300:3300'
    command: ["./wait-for.sh", "mongo:27017", "--", "yarn", "dev"]

  erxes-widgets-api:
    container_name: "erxes-widgets-api"
    build:
      dockerfile: ./Dockerfile.dev
      context: ../erxes-widgets-api
    volumes:
      - /erxes-widgets-api/node_modules
      - /erxes-widgets-api/.git
      - ../erxes-widgets-api/:/erxes-widgets-api
    env_file:
      ../erxes-widgets-api/.env
    depends_on:
      - "erxes-api"
    ports:
      - '3100:3100'
    command: ["./wait-for.sh", "mongo:27017", "--", "yarn", "dev"]

  erxes:
    container_name: "erxes"
    build:
      dockerfile: ./Dockerfile.dev
      context: ../erxes
    volumes:
      - /erxes/node_modules
      - /erxes/.git
      - ../erxes:/erxes
    env_file:
      ../erxes/.env
    ports:
      - '3000:3000'
    depends_on:
      - "erxes-api"

  erxes-widgets:
    container_name: "erxes-widgets"
    build:
      dockerfile: ./Dockerfile.dev
      context: ../erxes-widgets
    volumes:
      - /erxes-widgets/node_modules
      - /erxes-widgets/.git
      - ../erxes-widgets:/erxes-widgets
    env_file:
      ../erxes-widgets/.env
    ports:
      - '3200:3200'
    depends_on:
      - "erxes-widgets-api"

  nginx:
    container_name: "nginx"
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - "erxes"
      - "erxes-api"
      - "erxes-widgets-api"
      - "erxes-widgets"